-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 18:57:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hejevero3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hejevero3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hejevero3` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `hejevero3` ;

-- -----------------------------------------------------
-- Table `hejevero3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`user` (
  `Id_user` INT NOT NULL,
  `Cod_user` VARCHAR(45) NULL,
  `Nam_user` VARCHAR(45) NULL,
  `Lasn_user` VARCHAR(45) NULL,
  `Nick_user` VARCHAR(45) NULL,
  `Pass_user` VARCHAR(45) NULL,
  `Dat_user` VARCHAR(45) NULL,
  `Sta_user` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`level` (
  `Id_level` INT NOT NULL,
  `Nam_level` VARCHAR(45) NULL,
  `Sta_level` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`warehouse` (
  `Id_wh` INT NOT NULL,
  `Cod_wh` VARCHAR(45) NULL,
  `Nam_wh` VARCHAR(45) NULL,
  `Dat_wh` VARCHAR(45) NULL,
  `Cou_wh` VARCHAR(45) NULL,
  `Cit_wh` VARCHAR(45) NULL,
  `Dir_wh` VARCHAR(45) NULL,
  `Sta_wh` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_wh`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`level_user_warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`level_user_warehouse` (
  `Id_luw` INT NOT NULL,
  `Sta_luw` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `level_Id_level` INT NOT NULL,
  `warehouse_Id_wh` INT NOT NULL,
  PRIMARY KEY (`Id_luw`),
  INDEX `fk_level_user_warehouse_user1_idx` (`user_Id_user` ASC),
  INDEX `fk_level_user_warehouse_level1_idx` (`level_Id_level` ASC),
  INDEX `fk_level_user_warehouse_warehouse1_idx` (`warehouse_Id_wh` ASC),
  CONSTRAINT `fk_level_user_warehouse_user1`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero3`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_level_user_warehouse_level1`
    FOREIGN KEY (`level_Id_level`)
    REFERENCES `hejevero3`.`level` (`Id_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_level_user_warehouse_warehouse1`
    FOREIGN KEY (`warehouse_Id_wh`)
    REFERENCES `hejevero3`.`warehouse` (`Id_wh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`system` (
  `Id_sys` INT NOT NULL,
  `State_sys` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  `level_Id_level` INT NOT NULL,
  PRIMARY KEY (`Id_sys`),
  INDEX `fk_system_user1_idx` (`user_Id_user` ASC),
  INDEX `fk_system_level1_idx` (`level_Id_level` ASC),
  CONSTRAINT `fk_system_user1`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero3`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_level1`
    FOREIGN KEY (`level_Id_level`)
    REFERENCES `hejevero3`.`level` (`Id_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`function`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`function` (
  `Id_fun` INT NOT NULL,
  `Nam_fun` VARCHAR(45) NULL,
  `Sta_fun` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_fun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`priority` (
  `Id_pri` INT NOT NULL,
  `Pub_pri` VARCHAR(45) NULL,
  `Tab_pri` VARCHAR(45) NULL,
  `Sta_pri` VARCHAR(45) NULL,
  `function_Id_fun` INT NOT NULL,
  PRIMARY KEY (`Id_pri`),
  INDEX `fk_priority_function1_idx` (`function_Id_fun` ASC),
  CONSTRAINT `fk_priority_function1`
    FOREIGN KEY (`function_Id_fun`)
    REFERENCES `hejevero3`.`function` (`Id_fun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`level_priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`level_priority` (
  `Id_lp` INT NOT NULL,
  `Sta_lp` VARCHAR(5) NULL,
  `level_Id_level` INT NOT NULL,
  `priority_Id_pri` INT NOT NULL,
  PRIMARY KEY (`Id_lp`),
  INDEX `fk_level_priority_level1_idx` (`level_Id_level` ASC),
  INDEX `fk_level_priority_priority1_idx` (`priority_Id_pri` ASC),
  CONSTRAINT `fk_level_priority_level1`
    FOREIGN KEY (`level_Id_level`)
    REFERENCES `hejevero3`.`level` (`Id_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_level_priority_priority1`
    FOREIGN KEY (`priority_Id_pri`)
    REFERENCES `hejevero3`.`priority` (`Id_pri`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`record` (
  `Id_rec` INT NOT NULL,
  `Cod_rec` VARCHAR(45) NULL,
  `Nam_rec` VARCHAR(45) NULL,
  `Tab_rec` VARCHAR(45) NULL,
  `Id_Chan_rec` VARCHAR(45) NULL,
  `Sta_rec` VARCHAR(5) NULL,
  `user_Id_user` INT NOT NULL,
  PRIMARY KEY (`Id_rec`),
  INDEX `fk_record_user2_idx` (`user_Id_user` ASC),
  CONSTRAINT `fk_record_user2`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero3`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`product` (
  `Id_pro` INT NOT NULL,
  `Cod_pro` VARCHAR(45) NULL,
  `Nam_pro` VARCHAR(45) NULL,
  `Det_pro` VARCHAR(300) NULL,
  `Dat_pro` VARCHAR(45) NULL,
  `Stock_pro` VARCHAR(45) NULL,
  `Sta_pro` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`family` (
  `Id_fam` INT NOT NULL,
  `Nam_fam` VARCHAR(45) NULL,
  `Sta_fam` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_fam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`storage_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`storage_product` (
  `Id_sp` INT NOT NULL,
  `Dat_sp` VARCHAR(45) NULL,
  `Det_sp` VARCHAR(300) NULL,
  `Tot_sp` VARCHAR(45) NULL,
  `Qua_sp` VARCHAR(45) NULL,
  `Act_Stock_sp` VARCHAR(45) NULL,
  `Sta_sp` VARCHAR(5) NULL,
  `product_Id_pro` INT NOT NULL,
  `warehouse_Id_wh` INT NOT NULL,
  PRIMARY KEY (`Id_sp`),
  INDEX `fk_storage_product_product1_idx` (`product_Id_pro` ASC),
  INDEX `fk_storage_product_warehouse1_idx` (`warehouse_Id_wh` ASC),
  CONSTRAINT `fk_storage_product_product1`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero3`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storage_product_warehouse1`
    FOREIGN KEY (`warehouse_Id_wh`)
    REFERENCES `hejevero3`.`warehouse` (`Id_wh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`price` (
  `Id_price` INT NOT NULL,
  `Cod_price` VARCHAR(45) NULL,
  `Start_dat_price` VARCHAR(45) NULL,
  `End_dat_price` VARCHAR(45) NULL,
  `New_price` VARCHAR(45) NULL,
  `State_price` VARCHAR(5) NULL,
  `product_Id_pro` INT NOT NULL,
  PRIMARY KEY (`Id_price`),
  INDEX `fk_price_product2_idx` (`product_Id_pro` ASC),
  CONSTRAINT `fk_price_product2`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero3`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`product_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`product_family` (
  `Id_pf` INT NOT NULL,
  `sta_pf` VARCHAR(5) NULL,
  `family_Id_fam` INT NOT NULL,
  `product_Id_pro` INT NOT NULL,
  PRIMARY KEY (`Id_pf`),
  INDEX `fk_product_family_family1_idx` (`family_Id_fam` ASC),
  INDEX `fk_product_family_product1_idx` (`product_Id_pro` ASC),
  CONSTRAINT `fk_product_family_family1`
    FOREIGN KEY (`family_Id_fam`)
    REFERENCES `hejevero3`.`family` (`Id_fam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_family_product1`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero3`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`extra` (
  `Id_extra` INT NOT NULL,
  `name_extra` VARCHAR(45) NULL,
  `det_extra` VARCHAR(300) NULL,
  `typ_extra` VARCHAR(45) NULL,
  `sta_extra` VARCHAR(5) NULL,
  `product_Id_pro` INT NOT NULL,
  PRIMARY KEY (`Id_extra`),
  INDEX `fk_extra_product1_idx` (`product_Id_pro` ASC),
  CONSTRAINT `fk_extra_product1`
    FOREIGN KEY (`product_Id_pro`)
    REFERENCES `hejevero3`.`product` (`Id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hejevero3`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hejevero3`.`post` (
  `Id_post` INT NOT NULL,
  `Cod_post` VARCHAR(45) NULL,
  `Sta_post` VARCHAR(45) NULL,
  `user_Id_user` INT NOT NULL,
  PRIMARY KEY (`Id_post`),
  INDEX `fk_post_user1_idx` (`user_Id_user` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_Id_user`)
    REFERENCES `hejevero3`.`user` (`Id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
